# F5-TTS | E2-TTS
model = "F5-TTS"
ref_audio = "infer/examples/basic/test_1.wav"
# If an empty "", transcribes the reference audio automatically.
ref_text = "吃什么？吃什么呀？有没有推荐的？"
# 70字文本
gen_text = "我是奶龙，我是奶龙。"
# gen_text = "大斧VS，VK哥，你们知道吗？VK哥在诶罗格斯冠军赛前回应，大斧。如今我整装待发，充满正能量，让我们奔跑吧！C那帕克斯！你懂我的意思吗？"
# File with text to generate. Ignores the text above.
gen_file = ""
remove_silence = false
output_dir = "tests"